.include "../share/mk/top.mk"

# depend on 'test' target to make sure that we compile jvst and the unit
# tests before running the tests so the output looks a bit tidier
alltests: test allsuites unittests
